import unittest

from featurebroker import *
from config import Config
from filesystem import Filesystem


class CategoryTree:
    def __init__(self, root=''):
        self.children = []
        self.setRoot(root)

    def setRoot(self, root):
        self.root = root

    def insertChild(self, tree):
        self.children.append(tree)


def traverseTree(tree, func):
    def inner(tree, depth):
        func(tree, depth)
        if len(tree.children) == 0:
            pass
        else:
            for child in tree.children:
                inner(child, depth + 1)
    
    inner(tree, 0)

def printTree(tree):
    def printfunc(tree, depth):
        print ' ' * depth, tree.root
    traverseTree(tree, printfunc)

def compareTree(tree1, tree2):
    tree1result = []
    tree2result = []

    def tree1inner(tree, depth):
        tree1result.append((depth, tree.root))

    def tree2inner(tree, depth):
        tree2result.append((depth, tree.root))

    traverseTree(tree1, tree1inner)
    traverseTree(tree2, tree2inner)

    for item1, item2 in zip(tree1result, tree2result):
        if item1 != item2:
            print item1[1], 'not equal to', item2[1]
            return False
    return True


class Categories:
    filesystem = RequiredFeature('Filesystem')

    def __init__(self):
        self.categoryTree = CategoryTree()
        self.recurseList(self.filesystem.listDirs(['events', 'rugby']), self.categoryTree)

    def getTree(self):
        return self.categoryTree

    def searchList(self, needle, categoryList):
        for index, category in enumerate(categoryList):
            if category[0] == needle:
                return index
        return -1

    def recurseList(self, categoryList, tree):
        """
        Takes a list generated by Filesystem and turns it into
        tree form. It does this by recursively delving into the
        list and building the tree.
        """
        firstItem = categoryList[0]
        firstItemName = self.categoryName(firstItem[0])
        tree.setRoot(firstItemName)
        children = firstItem[1]
        if len(children) == 0:
            #return a tree with no children (a leaf essentially)
            return tree
        else:
            for child in children:
                path = self.filesystem.joinPath([firstItem[0], child])
                indexOfChild = self.searchList(path, categoryList)
                assert indexOfChild != -1, 'path not in categoryList'
                #categoryList[indexOfChild:] is a shorter categoryList
                #with only elements from the child dir onwards
                tree.insertChild(self.recurseList(categoryList[indexOfChild:], CategoryTree()))
            #return tree with children inserted
            return tree

    def categoryName(self, dirname):
        return self.filesystem.getBasename(dirname)


class CategoriesTests(unittest.TestCase):
    def makeTestTree(self):
        under7 = CategoryTree('under 7s')
        under7.insertChild(CategoryTree('Match 1'))
        under7.insertChild(CategoryTree('Match 2'))
        under8 = CategoryTree('under 8s')
        under9 = CategoryTree('under 9s')
        boys = CategoryTree('Boys')
        boys.insertChild(under7)
        boys.insertChild(under8)
        boys.insertChild(under9)
        under10 = CategoryTree('under 10s')
        over10 = CategoryTree('over 10s')
        girls = CategoryTree('Girls')
        girls.insertChild(under10)
        girls.insertChild(over10)
        rugby = CategoryTree('Rugby')
        rugby.insertChild(boys)
        rugby.insertChild(girls)
        return rugby
    
    def setUp(self):
        self.categories = Categories()

    def testBuildTree(self):
        self.assertTrue(compareTree(self.categories.categoryTree,
                                    self.makeTestTree()))


class MockFilesystem(Filesystem):
    def listDirs(self, dirname):
        return [
            ('events/Rugby', ['Boys', 'Girls'], []),
            ('events/Rugby/Boys', ['under 7s', 'under 8s', 'under 9s'], []),
            ('events/Rugby/Boys/under 7s', ['Match 1', 'Match 2'], []),
            ('events/Rugby/Boys/under 7s/Match 1', [], []),
            ('events/Rugby/Boys/under 7s/Match 2', [], []),
            ('events/Rugby/Boys/under 8s', [], []),
            ('events/Rugby/Boys/under 9s', [], []),
            ('events/Rugby/Girls', ['under 10s', 'over 10s'], []),
            ('events/Rugby/Girls/under 10s', [], []),
            ('events/Rugby/Girls/over 10s', [], []),
            ]


def suite():
    features.provide('Filesystem', MockFilesystem)
    features.provide('Config', Config)
    testSuite = unittest.makeSuite(CategoriesTests)
    return testSuite

    
def main():
    unittest.TextTestRunner().run(suite())

if __name__ == '__main__':
    main()
